DROP TABLE IF EXISTS exam;
DROP TABLE IF EXISTS exam_year;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS question_options;
DROP TABLE IF EXISTS result;
DROP TABLE IF EXISTS subject;
DROP TABLE IF EXISTS user_info;
DROP TABLE IF EXISTS country;
